In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('AIR_QUALITY.csv')

In [3]:
df.shape

(5811, 15)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5811 entries, 0 to 5810
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   RecordID             5811 non-null   int64  
 1   AQI                  5811 non-null   float64
 2   PM10                 5811 non-null   float64
 3   PM2_5                5811 non-null   float64
 4   NO2                  5811 non-null   float64
 5   SO2                  5811 non-null   float64
 6   O3                   5811 non-null   float64
 7   Temperature          5811 non-null   float64
 8   Humidity             5811 non-null   float64
 9   WindSpeed            5811 non-null   float64
 10  RespiratoryCases     5811 non-null   int64  
 11  CardiovascularCases  5811 non-null   int64  
 12  HospitalAdmissions   5811 non-null   int64  
 13  HealthImpactScore    5811 non-null   float64
 14  HealthImpactClass    5811 non-null   int64  
dtypes: float64(10), int64(5)
memory usage:

In [5]:
df['HealthImpactClass'].value_counts()

HealthImpactClass
0    4808
1     579
2     273
3      95
4      56
Name: count, dtype: int64

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

RecordID               0
AQI                    0
PM10                   0
PM2_5                  0
NO2                    0
SO2                    0
O3                     0
Temperature            0
Humidity               0
WindSpeed              0
RespiratoryCases       0
CardiovascularCases    0
HospitalAdmissions     0
HealthImpactScore      0
HealthImpactClass      0
dtype: int64

In [8]:
df.describe()

RecordID          AQI         PM10        PM2_5          NO2  \
count  5811.000000  5811.000000  5811.000000  5811.000000  5811.000000   
mean   2906.000000   248.438476   148.654997   100.223714   102.293445   
std    1677.635538   144.777638    85.698500    58.096612    57.713175   
min       1.000000     0.005817     0.015848     0.031549     0.009625   
25%    1453.500000   122.951293    75.374954    49.435171    53.538538   
50%    2906.000000   249.127841   147.634997   100.506337   102.987736   
75%    4358.500000   373.630668   222.436759   151.340260   151.658516   
max    5811.000000   499.858837   299.901962   199.984965   199.980195   

               SO2           O3  Temperature     Humidity    WindSpeed  \
count  5811.000000  5811.000000  5811.000000  5811.000000  5811.000000   
mean     49.456838   149.312431    14.975500    54.776853     9.989177   
std      28.530329    86.534240    14.483067    26.020786     5.776950   
min       0.011023     0.001661    -9.990998    10.001506     0.002094   
25%      24.887264    73.999665     2.481500    31.995262     4.952343   
50%      49.530165   149.559871    14.942428    54.543904    10.051742   
75%      73.346617   223.380126    27.465374    77.641639    14.971840   
max      99.969561   299.936811    39.963434    99.997493    19.999139   

       RespiratoryCases  CardiovascularCases  HospitalAdmissions  \
count       5811.000000          5811.000000         5811.000000   
mean           9.974187             4.988986            2.001033   
std            3.129234             2.216791            1.398794   
min            1.000000             0.000000            0.000000   
25%            8.000000             3.000000            1.000000   
50%           10.000000             5.000000            2.000000   
75%           12.000000             6.000000            3.000000   
max           23.000000            14.000000           12.000000   

       HealthImpactScore  HealthImpactClass  
count        5811.000000        5811.000000  
mean           93.785223           0.281191  
std            13.318904           0.714075  
min            22.448488           0.000000  
25%            98.203057           0.000000  
50%           100.000000           0.000000  
75%           100.000000           0.000000  
max           100.000000           4.000000

In [9]:
X = df.drop(columns=['HealthImpactClass'])
Y = df['HealthImpactClass']
X

RecordID         AQI        PM10       PM2_5         NO2        SO2  \
0            1  187.270059  295.853039   13.038560    6.639263  66.161150   
1            2  475.357153  246.254703    9.984497   16.318326  90.499523   
2            3  365.996971   84.443191   23.111340   96.317811  17.875850   
3            4  299.329242   21.020609   14.273403   81.234403  48.323616   
4            5   78.009320   16.987667  152.111623  121.235461  90.866167   
...        ...         ...         ...         ...         ...        ...   
5806      5807  171.112762   11.246387  197.984629  158.643107  17.743678   
5807      5808  490.691667  275.340762   55.774170  132.336871  29.334724   
5808      5809  314.841798   41.892699  184.708551   82.105823  68.334578   
5809      5810  208.080473  165.533785  199.177255  100.796385  87.586488   
5810      5811   83.269257   82.216262  119.968244  193.440691  79.849177   

              O3  Temperature   Humidity  WindSpeed  RespiratoryCases  \
0      54.624280     5.150335  84.424344   6.137755                 7   
1     169.621727     1.543378  46.851415   4.521422                10   
2       9.006794     1.169483  17.806977  11.157384                13   
3      93.161033    21.925276  99.473373  15.302500                 8   
4     241.795138     9.217517  24.906837  14.534733                 9   
...          ...          ...        ...        ...               ...   
5806  280.370909    37.359323  61.707640   4.097129                14   
5807  108.043492    34.532542  21.528555   6.682549                 8   
5808  105.568504    22.975564  92.725625   2.889698                12   
5809  166.469537    36.090620  25.836286  10.722393                 6   
5810   28.681885    18.239090  77.096194  16.410320                14   

      CardiovascularCases  HospitalAdmissions  HealthImpactScore  
0                       5                   1          97.244041  
1                       2                   0         100.000000  
2                       3                   0         100.000000  
3                       8                   1         100.000000  
4                       0                   1          95.182643  
...                   ...                 ...                ...  
5806                    5                   2         100.000000  
5807                    6                   2         100.000000  
5808                    2                   3         100.000000  
5809                    2                   3         100.000000  
5810                    2                   2          81.668298  

[5811 rows x 14 columns]

In [10]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
5806    4
5807    3
5808    1
5809    4
5810    0
Name: HealthImpactClass, Length: 5811, dtype: int64

In [11]:
X.shape,Y.shape

((5811, 14), (5811,))

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [13]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((4648, 14), (1163, 14), (4648,), (1163,))

In [14]:
X_train.shape[0] / X.shape[0],X_test.shape[0] / X.shape[0],Y_train.shape[0]/Y.shape[0],Y_test.shape[0]/Y.shape[0]

(0.7998623300636724,
 0.20013766993632764,
 0.7998623300636724,
 0.20013766993632764)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression(solver='liblinear', max_iter = 1000)

In [17]:
mymodel = LogisticRegression()

In [18]:
model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [19]:
model.coef_

array([[-6.46229268e-04,  3.96662204e-04, -4.35511908e-04,
        -2.27790104e-04, -6.77176172e-04, -1.86947262e-03,
        -3.97824696e-04,  3.91164835e-04, -4.47566538e-03,
         4.61821275e-03, -6.20747628e-02, -5.71748986e-02,
        -7.60196353e-02,  1.79187400e-01],
       [ 6.71246969e-05, -1.55706889e-02, -3.57477079e-03,
        -5.99215464e-03, -3.60126048e-03, -1.82889825e-04,
        -3.45308942e-03,  1.98694139e-03,  7.23906415e-03,
         5.45681798e-03,  5.23324845e-02,  3.89021067e-02,
         7.27458667e-02,  5.61272489e-03],
       [ 4.75734914e-04,  3.84796219e-04,  9.56285918e-04,
        -1.94340186e-03,  2.44815208e-03,  5.64683068e-03,
         1.05416639e-03,  1.82723705e-02,  1.44524397e-03,
         3.06808960e-02,  1.24407458e-01,  1.21210148e-01,
         2.18099589e-02, -9.80061857e-02],
       [ 8.66238879e-04,  5.41396686e-03, -1.75683135e-03,
        -3.07509892e-03, -9.37879444e-04, -3.38302229e-03,
        -5.97553076e-04, -1.99208460e-02, -2.

In [20]:
model.intercept_

array([-1.09150944e+01,  5.31769072e-02,  1.51459474e-01, -7.54845457e-03,
       -4.59688172e+00])

In [21]:
probabilities = model.predict_proba(X_train).round(5)

In [22]:
probabilities.shape

(4648, 5)

In [23]:
(probabilities[:,1] > 0.5)*1

array([0, 1, 0, ..., 0, 0, 0])

In [24]:
model.predict(X_train)

array([0, 1, 0, ..., 0, 0, 2], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [26]:
accuracy_score(Y_train,model.predict(X_train))

0.8898450946643718

In [27]:
accuracy_score(Y_test,model.predict(X_test))

0.9002579535683577

In [28]:
confusion_matrix(Y_train,model.predict(X_train))

array([[3817,   21,    4,    0,    0],
       [ 204,  254,   13,    0,    1],
       [  46,  109,   63,    0,    0],
       [  34,   13,   20,    1,    0],
       [  38,    6,    3,    0,    1]], dtype=int64)

In [29]:
confusion_matrix(Y_test,model.predict(X_test))

array([[961,   4,   1,   0,   0],
       [ 38,  61,   8,   0,   0],
       [  8,  22,  25,   0,   0],
       [ 11,   7,   9,   0,   0],
       [  7,   0,   1,   0,   0]], dtype=int64)

In [30]:
print(classification_report(Y_train,model.predict(X_train)))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96      3842
           1       0.63      0.54      0.58       472
           2       0.61      0.29      0.39       218
           3       1.00      0.01      0.03        68
           4       0.50      0.02      0.04        48

    accuracy                           0.89      4648
   macro avg       0.73      0.37      0.40      4648
weighted avg       0.87      0.89      0.87      4648



In [31]:
print(classification_report(Y_test,model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97       966
           1       0.65      0.57      0.61       107
           2       0.57      0.45      0.51        55
           3       0.00      0.00      0.00        27
           4       0.00      0.00      0.00         8

    accuracy                           0.90      1163
   macro avg       0.43      0.40      0.42      1163
weighted avg       0.87      0.90      0.88      1163



C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
CONCLUSION:-

################################################################DONE###############################################